# Generated by Django 5.0.2 on 2024-03-19 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_like_like_unique_like_per_user_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
