# Generated by Django 5.0.2 on 2024-02-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_body_part_alter_user_first_name_and_more'),
        ('users', '0005_remove_user_body_part_remove_user_height_and_more'),
    ]

    operations = [
    ]
